backup, improved init script, install script
git-svn-id: http://wanfailoverscript.googlecode.com/svn/trunk@13 66989f9f-ffbd-eb33-a4e1-7d92d0df9447

diff --git a/wfs b/wfs
--- a/wfs
+++ b/wfs
@@ -27,6 +27,7 @@ else
     PIDFILE=/var/run/wfs.pid
 fi
 
+
 PRIMARY_TARGET_FAILED=0
 SECONDARY_TARGET_FAILED=0
 ACTIVE_CONNECTION=""
@@ -71,6 +72,14 @@ log2syslog () {
 
     echo "$1" | logger
 }
+
+
+if [ -e "$PIDFILE" ]
+then
+    log2dsply "PID file $PIDFILE exists. Aborting."
+    log2syslog "PID file $PIDFILE exists. Aborting"
+    exit 1
+fi
 
 route_del () {
 
