Major rework, now releasing 2.0...
git-svn-id: http://wanfailoverscript.googlecode.com/svn/trunk@19 66989f9f-ffbd-eb33-a4e1-7d92d0df9447

diff --git a/wfs b/wfs
--- a/wfs
+++ b/wfs
@@ -8,28 +8,30 @@
 #
 
 VERSION=1.20
-CONFIG=/etc/wfs.conf
 
-if [ -e "$CONFIG" ]
+CONFIG=/etc/wfs
+CONFIG_FILE="$CONFIG/wfs.conf"
+
+if [ -e "$CONFIG_FILE" ]
 then
-    . $CONFIG
+    . $CONFIG_FILE
 else
-    TARGET_FILE="targets.txt"
-    TARGETS=`cat "$TARGET_FILE"`
+    TARGETS_FILE="$CONFIG/targets.txt"
     PRIMARY_GW=10.0.0.1
     SECONDARY_GW=10.0.0.200
-    INTERVAL=25
-    COUNT=2
-    DISTANCE=15
+    INTERVAL=20
+    TEST_COUNT=2
     THRESHOLD=3
     COOLDOWNDELAY=20
     MAIL_TARGET=""
     DAEMON=1
+    QUIET=0
     PIDFILE=/var/run/wfs.pid
 fi
 
-TARGET_FAILED=0
+TARGETS_FAILED=0
 ACTIVE_CONNECTION=""
+TEST_INTERVAL="$INTERVAL"
 
 #
 # If some command must be run after a failover or restore, please specify
@@ -40,7 +42,6 @@ SECONDARY_CMD=""
 
 # --- do not change anything below ---
 
-
 route -n | grep -w "$PRIMARY_GW" | grep -w "0.0.0.0" >> /dev/null 2>&1
 if [ "$?" == "0" ]
 then
@@ -49,80 +50,135 @@ else
     ACTIVE_CONNECTION=SECONDARY
 fi
 
-log2dsply () {
-    
-    if [ "$QUIET" == "0" ]
-    then
-        echo "$1" 
-    fi
+log () {
+
+    TYPE="$1"
+    MSG="$2"
+    DATE=`date +%b\ %d\ %H:%M:%S`
+    case "$TYPE" in
+        "ERROR" )
+                    echo "$DATE $MSG" 
+                    log2syslog "$TYPE $MSG"
+                    ;;
+        "DEBUG" )
+                    if [ "$DEBUG" = "1" ]
+                    then
+                        echo "$DATE $MSG"
+                        log2syslog "$TYPE $MSG"
+                    fi
+                    
+                    ;;
+        "INFO" )
+                    if [ "$QUIET" == "0" ] 
+                    then
+                        echo "$DATE $MSG" 
+                    fi
+                    log2syslog "$TYPE $MSG"
+                    ;;
+    esac
 }
 
 log2mail () {
 
     SUBJECT="$1"
     BODY="$2"
+    DATE=`date +%b\ %d\ %H:%M:%S`
     if [ ! -z "$MAIL_TARGET" ]
     then
-        echo "$BODY" | mail -s "$SUBJECT" "$MAIL_TARGET" &
+        echo "$DATE - $BODY" | mail -s "$SUBJECT" "$MAIL_TARGET" &
     fi
 }
 
 log2syslog () {
 
-    echo "$1" | logger
+    echo "$1" | logger -t "WFS"
+}
+
+init_wfs () {
+
+    if [ ! -e "$TARGETS_FILE" ]
+    then
+        log ERROR "Targets file $TARGETS_FILE does not exist."
+        exit 1
+    else
+        TARGETS=`cat "$TARGETS_FILE"`
+        TMPVAR=( $TARGETS )
+        NO_OF_TARGETS=${#TMPVAR[@]}
+    fi
+
+    if [ -z "$TARGETS" ]
+    then
+        echo "No targets to test availability, targets file $TARGETS_FILE empty?."
+        exit 1
+    else
+        for x in $TARGETS
+        do
+            log DEBUG "Adding static route for host $x"
+            route add -host "$x" gw "$PRIMARY_GW" >> /dev/null 2>&1
+        done
+    fi
 }
 
 
-if [ -e "$PIDFILE" ]
-then
-    log2dsply "PID file $PIDFILE exists. Aborting."
-    log2syslog "PID file $PIDFILE exists. Aborting"
-    exit 1
-fi
+check_for_pid () {
+
+    if [ -e "$PIDFILE" ]
+    then
+        log ERROR "PID file $PIDFILE exists. Aborting."
+        exit 1
+    fi
+}
 
 route_del () {
 
     route del default gw "$1"
 }
 
-if [ "$DEBUG" == "1" ]
-then
-    log2dsply "Currently active WAN link: $ACTIVE_CONNECTION"
-fi
+display_header () {
+
+    log INFO "------------------------------"
+    log INFO " WAN Failover Script $VERSION" 
+    log INFO "------------------------------"
+    log INFO " Primary gateway: $PRIMARY_GATEWAY"
+    log INFO " Secondary gateway: $SECONDARY_GATEWAY"
+    log INFO " Threshold before failover: $THRESHOLD"
+    log INFO " Number of target hosts: $NO_OF_TARGETS"
+    log INFO " Tests per host: $TEST_COUNT"
+    log INFO "------------------------------"
+}
+
 
 #
 # This route allows testing if the failed primary link
 # Is available again, when in failover mode.
 #
-route add -host "$PRIMARY_TARGET" gw "$PRIMARY_GW" >> /dev/null 2>&1
-route add -host "$SECONDARY_TARGET" gw "$PRIMARY_GW" >> /dev/null 2>&1
+
 
 test_single_target () {
 
     TARGET="$1"
+    log DEBUG "Test interval between hosts is $TEST_INTERVAL"
 
-    ping -c "$COUNT" "$TARGET" >> /dev/null 2>&1
+    ping -c "$TEST_COUNT" "$TARGET" >> /dev/null 2>&1
     if [ ! "$?" == "0" ]
     then
-        if [ "$DEBUG" == "1" ]
+        log INFO "Host $HOST UNREACHABLE"
+
+        if [ "$TARGETS_FAILED" -lt "$THRESHOLD" ]
         then
-            log2dsply "Host $HOST UNREACHABLE"
-            log2syslog "Host $HOST UNREACHABLE"
+            ((TARGETS_FAILED++)) 
         fi
-
-        ((TARGET_FAILED++)) 
-        DISTANCE=5
-
+        TEST_INTERVAL=5
     else
-        if [ "$TARGET_FAILED" -gt "0" ] 
+        if [ "$TARGETS_FAILED" -gt "0" ] 
         then
-            ((TARGET_FAILED--))
+            ((TARGETS_FAILED--))
         fi
 
-        if [ "$DEBUG" == "1" ]
+        log DEBUG "Host $TARGET OK"
+        if [ "$ACTIVE_CONNECTION" = "PRIMARY" ]
         then
-            log2dsply "Host $TARGET OK"
-            log2syslog "Host $TARGET OK"
+            TEST_INTERVAL="$INTERVAL"
         fi
     fi
 }
@@ -133,11 +189,14 @@ test_wan_status () {
     for x in $TARGETS
     do
         test_single_target $x
+        if [ "$TARGETS_FAILED" -gt "0" ]
+        then
+            log INFO "Failed targets is $TARGETS_FAILED, threshold is $THRESHOLD."
+        fi
         check_wan_status
-        sleep "$DISTANCE"
+        sleep "$TEST_INTERVAL"
     done
 }
-
 
 route_add () {
 
@@ -160,31 +219,25 @@ switch_to_secondary () {
 
 check_wan_status () {
 
-    if [ "$TARGET_FAILED" -ge "$THRESHOLD" ] && [ "$ACTIVE_CONNECTION" == "PRIMARY" ]
+    if [ "$TARGETS_FAILED" -ge "$THRESHOLD" ] && [ "$ACTIVE_CONNECTION" == "PRIMARY" ]
     then
         MSG="Primary WAN link failed. Switched to secondary link."
         BODY=`route -n`
         log2mail "$MSG" "$BODY"
-        log2dsply "$MSG"
-        log2syslog "$MSG"
+        log INFO "$MSG"
         switch
     elif [ "$ACTIVE_CONNECTION" == "SECONDARY" ] 
     then
-        if [ "$TARGET_FAILED" == "0" ] 
+        if [ "$TARGETS_FAILED" == "0" ] 
         then
             MSG="Primary WAN link OK. Switched back to primary link."
             BODY=`route -n`
             log2mail "$MSG" "$BODY"
-            log2dsply "$MSG"
-            log2syslog "$MSG"
+            log INFO "$MSG"
             switch
         fi
     else
-        if [ "$DEBUG" = "1" ]
-        then
-            log2dsply "WAN Link: $ACTIVE_CONNECTION"
-            log2syslog "WAN Link: $ACTIVE_CONNECTION"
-        fi
+        log INFO "WAN Link: $ACTIVE_CONNECTION"
     fi
 }
 
@@ -210,25 +263,24 @@ switch () {
 
 start_wfs () {
 
+    display_header
+    init_wfs
+
+    log INFO "Starting monitoring of WAN link."
+
     while true
     do
         test_wan_status
-        sleep "$INTERVAL"
     done
 }
 
+
 if [ "$DAEMON" == "0" ]
 then
-    log2dsply "* Starting monitoring of WAN link. *"
-    log2syslog "*** Starting monitoring of WAN link. ***"
+    check_for_pid
     start_wfs
 else
-    log2syslog "*** Starting monitoring of WAN link. ***"
+    check_for_pid
     start_wfs &
     echo "$!" > "$PIDFILE"
 fi
-    
-
-
-
-
